[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[browser]
gatherUsageStats = false 